# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the trunk branch
on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]

env:
  AZURE_FUNCTIONAPP_NAME_GET: 'fncGetRatings'  # set this to your application's name
  AZURE_FUNCTIONAPP_PACKAGE_PATH_GET: './fncGetRatings'    # set this to the path to your web app project, defaults to the repository root
  AZURE_FUNCTIONAPP_NAME_CREATE: 'fncCreateRating'  # set this to your application's name
  AZURE_FUNCTIONAPP_PACKAGE_PATH_CREATE: './CreateRating/Creatrating'    # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '3.1'              # set this to the dotnet version to use

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v2

    - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - uses: azure/login@v1.1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    ##
    # "Get" functions
    ##
    - name: 'Resolve Project Dependencies Using Dotnet - Get functions'
      shell: pwsh
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH_GET }}'
        dotnet build --configuration Release --output ./output
        popd
        
    - name: 'Run Azure Functions Action - Get functions'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME_GET }}
        package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH_GET }}/output'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}

    ##
    # "Create" functions
    ##
    - name: 'Resolve Project Dependencies Using Dotnet - Create functions'
      shell: pwsh
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH_CREATE }}'
        dotnet build --configuration Release --output ./output
        popd
        
    - name: 'Run Azure Functions Action - Create functions'
      uses: Azure/functions-action@v1
      id: fb
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME_CREATE }}
        package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH_CREATE }}/output'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}

